-- Historical filename retained so deployment inventories do not break.
-- The reversible administrator credential design has been retired. Do not add
-- password_encrypted on new or hash-only deployments.
