-- Role tag library: isolated from project_tag and talent_profile user data.
-- Idempotent on MySQL 8.0+. Each active project role receives 70 shared + 35 role-specific tags.

CREATE TABLE IF NOT EXISTS `talent_role_tag` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tag_text` VARCHAR(32) NOT NULL,
  `emoji` VARCHAR(16) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 1,
  `sort_order` INT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_talent_role_tag_text` (`tag_text`),
  KEY `idx_talent_role_tag_status_text` (`status`, `tag_text`),
  KEY `idx_talent_role_tag_status_sort` (`status`, `sort_order`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='人才名片角色推荐标签库';

CREATE TABLE IF NOT EXISTS `talent_role_tag_relation` (
  `tag_id` BIGINT UNSIGNED NOT NULL,
  `role_code` VARCHAR(32) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`tag_id`, `role_code`),
  KEY `idx_talent_role_tag_relation_role` (`role_code`, `tag_id`),
  CONSTRAINT `fk_talent_role_tag_relation_tag` FOREIGN KEY (`tag_id`) REFERENCES `talent_role_tag` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_talent_role_tag_relation_role` FOREIGN KEY (`role_code`) REFERENCES `project_role` (`code`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='人才推荐标签与项目角色多对多关系';

DROP TEMPORARY TABLE IF EXISTS `tmp_talent_role_tag_seed`;
CREATE TEMPORARY TABLE `tmp_talent_role_tag_seed` (
  `tag_text` VARCHAR(32) NOT NULL,
  `emoji` VARCHAR(16) NOT NULL,
  `role_code` VARCHAR(32) NULL,
  `sort_order` INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `tmp_talent_role_tag_seed` (`emoji`, `tag_text`, `role_code`, `sort_order`) VALUES
  ('🤝','沟通表达',NULL,1),
  ('🧩','团队协作',NULL,2),
  ('⚡','执行力',NULL,3),
  ('⏱️','时间管理',NULL,4),
  ('🎯','目标管理',NULL,5),
  ('🛡️','责任心',NULL,6),
  ('🚀','主动性',NULL,7),
  ('📚','学习能力',NULL,8),
  ('🧠','问题解决',NULL,9),
  ('💡','创新思维',NULL,10),
  ('🔍','逻辑思维',NULL,11),
  ('⚖️','批判思维',NULL,12),
  ('📊','数据意识',NULL,13),
  ('👤','用户思维',NULL,14),
  ('📋','项目管理',NULL,15),
  ('📝','需求分析',NULL,16),
  ('🔗','资源整合',NULL,17),
  ('🌐','跨部门协作',NULL,18),
  ('🗓️','会议组织',NULL,19),
  ('🪜','任务拆解',NULL,20),
  ('📈','进度跟踪',NULL,21),
  ('🔄','复盘总结',NULL,22),
  ('🗂️','文档沉淀',NULL,23),
  ('🔎','信息检索',NULL,24),
  ('🧪','调研分析',NULL,25),
  ('🎤','演讲展示',NULL,26),
  ('📣','汇报能力',NULL,27),
  ('🤝','谈判沟通',NULL,28),
  ('🕊️','冲突协调',NULL,29),
  ('🌤️','情绪管理',NULL,30),
  ('🏋️','抗压能力',NULL,31),
  ('🌱','适应能力',NULL,32),
  ('🏃','快速上手',NULL,33),
  ('🔬','细节把控',NULL,34),
  ('✅','质量意识',NULL,35),
  ('⚠️','风险意识',NULL,36),
  ('💰','成本意识',NULL,37),
  ('🏁','结果导向',NULL,38),
  ('💞','同理心',NULL,39),
  ('🙋','服务意识',NULL,40),
  ('🎈','团队氛围',NULL,41),
  ('🧑‍🏫','知识分享',NULL,42),
  ('🌟','导师意识',NULL,43),
  ('🔥','自我驱动',NULL,44),
  ('🛠️','持续改进',NULL,45),
  ('🤍','诚信可靠',NULL,46),
  ('⌚','守时守信',NULL,47),
  ('🪡','耐心细致',NULL,48),
  ('👀','观察力',NULL,49),
  ('🔭','洞察力',NULL,50),
  ('🧭','判断力',NULL,51),
  ('🗳️','决策力',NULL,52),
  ('🧱','组织协调',NULL,53),
  ('🗺️','统筹规划',NULL,54),
  ('🔢','优先级管理',NULL,55),
  ('🎛️','多任务处理',NULL,56),
  ('💻','远程协作',NULL,57),
  ('🌏','跨文化沟通',NULL,58),
  ('🏫','校园资源链接',NULL,59),
  ('🏆','竞赛经验',NULL,60),
  ('🌱','创业实践',NULL,61),
  ('🔬','科研协作',NULL,62),
  ('❤️','公益实践',NULL,63),
  ('🎪','活动执行',NULL,64),
  ('✍️','内容表达',NULL,65),
  ('🖥️','办公软件',NULL,66),
  ('📉','表格分析',NULL,67),
  ('🎨','视觉表达',NULL,68),
  ('🌍','英文沟通',NULL,69),
  ('🗣️','公开表达',NULL,70),
  ('🧭','领导力','TEAM_LEADER',101),
  ('🌄','愿景规划','TEAM_LEADER',102),
  ('♟️','战略思考','TEAM_LEADER',103),
  ('🏗️','团队搭建','TEAM_LEADER',104),
  ('🧑‍🤝‍🧑','角色分工','TEAM_LEADER',105),
  ('🔑','授权管理','TEAM_LEADER',106),
  ('🌳','人才培养','TEAM_LEADER',107),
  ('📣','激励团队','TEAM_LEADER',108),
  ('🏛️','文化建设','TEAM_LEADER',109),
  ('🔨','关键决策','TEAM_LEADER',110),
  ('🌐','全局视角','TEAM_LEADER',111),
  ('🧮','资源配置','TEAM_LEADER',112),
  ('⚖️','利益协调','TEAM_LEADER',113),
  ('🚨','危机管理','TEAM_LEADER',114),
  ('🔁','变革管理','TEAM_LEADER',115),
  ('🚩','项目立项','TEAM_LEADER',116),
  ('🛣️','里程碑规划','TEAM_LEADER',117),
  ('💬','绩效反馈','TEAM_LEADER',118),
  ('☕','一对一沟通','TEAM_LEADER',119),
  ('🎙️','主持会议','TEAM_LEADER',120),
  ('🤵','对外代表','TEAM_LEADER',121),
  ('🤝','合作拓展','TEAM_LEADER',122),
  ('🏫','校方沟通','TEAM_LEADER',123),
  ('💼','赞助洽谈','TEAM_LEADER',124),
  ('💹','商业模式','TEAM_LEADER',125),
  ('💰','预算统筹','TEAM_LEADER',126),
  ('🏅','成果验收','TEAM_LEADER',127),
  ('🪞','团队复盘','TEAM_LEADER',128),
  ('🌱','接班人培养','TEAM_LEADER',129),
  ('🔥','使命感','TEAM_LEADER',130),
  ('🚀','创业领导','TEAM_LEADER',131),
  ('🧲','共识凝聚','TEAM_LEADER',132),
  ('🚧','边界管理','TEAM_LEADER',133),
  ('🥁','节奏掌控','TEAM_LEADER',134),
  ('👑','领导者心态','TEAM_LEADER',135),
  ('🏛️','架构设计','TECH_LEADER',101),
  ('📏','代码规范','TECH_LEADER',102),
  ('🚄','性能优化','TECH_LEADER',103),
  ('🔐','信息安全','TECH_LEADER',104),
  ('🗄️','数据库设计','TECH_LEADER',105),
  ('🔌','接口设计','TECH_LEADER',106),
  ('☁️','云服务','TECH_LEADER',107),
  ('🧰','技术选型','TECH_LEADER',108),
  ('🧪','自动化测试','TECH_LEADER',109),
  ('🔁','持续集成','TECH_LEADER',110),
  ('🚢','持续交付','TECH_LEADER',111),
  ('🐛','故障排查','TECH_LEADER',112),
  ('📟','系统监控','TECH_LEADER',113),
  ('📈','容量规划','TECH_LEADER',114),
  ('🧱','模块化设计','TECH_LEADER',115),
  ('🔀','版本控制','TECH_LEADER',116),
  ('👀','代码审查','TECH_LEADER',117),
  ('📖','技术文档','TECH_LEADER',118),
  ('🧑‍💻','前端开发','TECH_LEADER',119),
  ('⚙️','后端开发','TECH_LEADER',120),
  ('📱','小程序开发','TECH_LEADER',121),
  ('🧠','算法设计','TECH_LEADER',122),
  ('🤖','人工智能','TECH_LEADER',123),
  ('🧬','机器学习','TECH_LEADER',124),
  ('📊','数据工程','TECH_LEADER',125),
  ('🛡️','权限设计','TECH_LEADER',126),
  ('🔒','隐私保护','TECH_LEADER',127),
  ('🧯','容灾设计','TECH_LEADER',128),
  ('🧹','技术债治理','TECH_LEADER',129),
  ('🧭','技术路线','TECH_LEADER',130),
  ('👨‍🏫','技术带教','TECH_LEADER',131),
  ('🧑‍🔬','技术预研','TECH_LEADER',132),
  ('🔧','开发工具链','TECH_LEADER',133),
  ('📦','发布管理','TECH_LEADER',134),
  ('🧑‍🚒','线上应急','TECH_LEADER',135),
  ('📈','用户增长','OPERATIONS_LEADER',101),
  ('🎪','活动策划','OPERATIONS_LEADER',102),
  ('👥','社群运营','OPERATIONS_LEADER',103),
  ('🧪','增长实验','OPERATIONS_LEADER',104),
  ('🪜','用户转化','OPERATIONS_LEADER',105),
  ('🔁','用户留存','OPERATIONS_LEADER',106),
  ('💬','用户反馈','OPERATIONS_LEADER',107),
  ('🗺️','用户旅程','OPERATIONS_LEADER',108),
  ('📊','运营数据分析','OPERATIONS_LEADER',109),
  ('🎯','指标体系','OPERATIONS_LEADER',110),
  ('🧑‍💼','用户分层','OPERATIONS_LEADER',111),
  ('🪙','激励机制','OPERATIONS_LEADER',112),
  ('📝','运营SOP','OPERATIONS_LEADER',113),
  ('📆','运营排期','OPERATIONS_LEADER',114),
  ('📦','渠道运营','OPERATIONS_LEADER',115),
  ('🤝','商务合作','OPERATIONS_LEADER',116),
  ('🏫','校园推广','OPERATIONS_LEADER',117),
  ('🧑‍🤝‍🧑','大使体系','OPERATIONS_LEADER',118),
  ('🎟️','报名转化','OPERATIONS_LEADER',119),
  ('📮','触达策略','OPERATIONS_LEADER',120),
  ('📱','私域运营','OPERATIONS_LEADER',121),
  ('🛒','商业化运营','OPERATIONS_LEADER',122),
  ('🧾','订单运营','OPERATIONS_LEADER',123),
  ('☎️','客服体系','OPERATIONS_LEADER',124),
  ('🧯','舆情响应','OPERATIONS_LEADER',125),
  ('🔍','竞品运营分析','OPERATIONS_LEADER',126),
  ('🌡️','活跃度提升','OPERATIONS_LEADER',127),
  ('🧲','裂变传播','OPERATIONS_LEADER',128),
  ('🎁','福利设计','OPERATIONS_LEADER',129),
  ('🏷️','内容分发','OPERATIONS_LEADER',130),
  ('🧭','渠道策略','OPERATIONS_LEADER',131),
  ('🪄','场景运营','OPERATIONS_LEADER',132),
  ('📣','召回运营','OPERATIONS_LEADER',133),
  ('🧹','流程优化','OPERATIONS_LEADER',134),
  ('📋','运营复盘','OPERATIONS_LEADER',135),
  ('✍️','文案策划','PUBLICITY_LEADER',101),
  ('📱','新媒体运营','PUBLICITY_LEADER',102),
  ('📰','新闻稿写作','PUBLICITY_LEADER',103),
  ('🎬','短视频策划','PUBLICITY_LEADER',104),
  ('🎞️','视频剪辑','PUBLICITY_LEADER',105),
  ('📷','摄影摄像','PUBLICITY_LEADER',106),
  ('🎙️','采访策划','PUBLICITY_LEADER',107),
  ('📡','媒体联络','PUBLICITY_LEADER',108),
  ('🗓️','内容日历','PUBLICITY_LEADER',109),
  ('🎯','传播策略','PUBLICITY_LEADER',110),
  ('📖','品牌故事','PUBLICITY_LEADER',111),
  ('📢','品牌传播','PUBLICITY_LEADER',112),
  ('🧷','品牌定位','PUBLICITY_LEADER',113),
  ('🧠','选题策划','PUBLICITY_LEADER',114),
  ('🔥','热点追踪','PUBLICITY_LEADER',115),
  ('🔖','标题创作','PUBLICITY_LEADER',116),
  ('🪶','长文写作','PUBLICITY_LEADER',117),
  ('🎤','口播表达','PUBLICITY_LEADER',118),
  ('📻','播客制作','PUBLICITY_LEADER',119),
  ('🖼️','海报策划','PUBLICITY_LEADER',120),
  ('📊','传播数据分析','PUBLICITY_LEADER',121),
  ('🔍','SEO基础','PUBLICITY_LEADER',122),
  ('🏷️','话题运营','PUBLICITY_LEADER',123),
  ('🤳','达人合作','PUBLICITY_LEADER',124),
  ('📣','校园宣发','PUBLICITY_LEADER',125),
  ('🧯','公关应对','PUBLICITY_LEADER',126),
  ('🪄','创意传播','PUBLICITY_LEADER',127),
  ('🧵','故事化表达','PUBLICITY_LEADER',128),
  ('📑','宣传方案','PUBLICITY_LEADER',129),
  ('🗃️','素材管理','PUBLICITY_LEADER',130),
  ('🎥','直播策划','PUBLICITY_LEADER',131),
  ('📝','脚本创作','PUBLICITY_LEADER',132),
  ('🗣️','社交媒体语感','PUBLICITY_LEADER',133),
  ('🌐','全渠道传播','PUBLICITY_LEADER',134),
  ('🔄','内容复盘','PUBLICITY_LEADER',135),
  ('🎨','UI设计','DESIGN_LEADER',101),
  ('🖱️','交互体验','DESIGN_LEADER',102),
  ('📐','排版美化','DESIGN_LEADER',103),
  ('🧩','设计系统','DESIGN_LEADER',104),
  ('🪄','视觉创意','DESIGN_LEADER',105),
  ('🧭','信息架构','DESIGN_LEADER',106),
  ('🧪','可用性测试','DESIGN_LEADER',107),
  ('📱','移动端设计','DESIGN_LEADER',108),
  ('🖥️','网页设计','DESIGN_LEADER',109),
  ('🧷','品牌视觉','DESIGN_LEADER',110),
  ('🪪','Logo设计','DESIGN_LEADER',111),
  ('🖼️','海报设计','DESIGN_LEADER',112),
  ('📊','信息可视化','DESIGN_LEADER',113),
  ('✏️','插画设计','DESIGN_LEADER',114),
  ('📦','包装设计','DESIGN_LEADER',115),
  ('🧱','组件规范','DESIGN_LEADER',116),
  ('🎚️','设计变量','DESIGN_LEADER',117),
  ('🌈','色彩搭配','DESIGN_LEADER',118),
  ('🔤','字体设计','DESIGN_LEADER',119),
  ('📏','栅格系统','DESIGN_LEADER',120),
  ('🖍️','图标设计','DESIGN_LEADER',121),
  ('🧰','Figma','DESIGN_LEADER',122),
  ('🪄','原型设计','DESIGN_LEADER',123),
  ('🗺️','用户流程','DESIGN_LEADER',124),
  ('♿','无障碍设计','DESIGN_LEADER',125),
  ('📸','图片处理','DESIGN_LEADER',126),
  ('🎞️','动效设计','DESIGN_LEADER',127),
  ('🧊','三维设计','DESIGN_LEADER',128),
  ('🔍','设计走查','DESIGN_LEADER',129),
  ('🤝','设计交付','DESIGN_LEADER',130),
  ('📚','设计资产管理','DESIGN_LEADER',131),
  ('🧠','设计思维','DESIGN_LEADER',132),
  ('👁️','审美判断','DESIGN_LEADER',133),
  ('🧹','界面一致性','DESIGN_LEADER',134),
  ('🎯','转化型设计','DESIGN_LEADER',135),
  ('📜','合同审核','LEGAL_LEADER',101),
  ('🛡️','风险控制','LEGAL_LEADER',102),
  ('⚖️','合规管理','LEGAL_LEADER',103),
  ('🔏','知识产权','LEGAL_LEADER',104),
  ('🔒','数据合规','LEGAL_LEADER',105),
  ('🕵️','隐私合规','LEGAL_LEADER',106),
  ('📝','条款起草','LEGAL_LEADER',107),
  ('🧾','法律检索','LEGAL_LEADER',108),
  ('📚','法规研究','LEGAL_LEADER',109),
  ('🤝','合同谈判','LEGAL_LEADER',110),
  ('🏷️','商标保护','LEGAL_LEADER',111),
  ('©️','著作权保护','LEGAL_LEADER',112),
  ('💡','专利基础','LEGAL_LEADER',113),
  ('🧑‍⚖️','争议处理','LEGAL_LEADER',114),
  ('📋','证据管理','LEGAL_LEADER',115),
  ('🚨','法律风险排查','LEGAL_LEADER',116),
  ('✅','合规审查','LEGAL_LEADER',117),
  ('🏫','校园活动合规','LEGAL_LEADER',118),
  ('📢','广告合规','LEGAL_LEADER',119),
  ('👥','劳动用工基础','LEGAL_LEADER',120),
  ('💰','财税合规基础','LEGAL_LEADER',121),
  ('🔐','保密协议','LEGAL_LEADER',122),
  ('📄','授权书管理','LEGAL_LEADER',123),
  ('🗂️','合同台账','LEGAL_LEADER',124),
  ('⏰','履约跟踪','LEGAL_LEADER',125),
  ('🧯','危机法务','LEGAL_LEADER',126),
  ('🌐','平台规则治理','LEGAL_LEADER',127),
  ('📑','政策解读','LEGAL_LEADER',128),
  ('🪪','主体资质核验','LEGAL_LEADER',129),
  ('🧭','合规流程设计','LEGAL_LEADER',130),
  ('🎓','普法培训','LEGAL_LEADER',131),
  ('🤖','AI合规意识','LEGAL_LEADER',132),
  ('🛒','消费者权益','LEGAL_LEADER',133),
  ('🔍','尽职调查','LEGAL_LEADER',134),
  ('🪶','法律文书写作','LEGAL_LEADER',135),
  ('🔍','人才筛选','RECRUITMENT_LEADER',101),
  ('🎤','面试技巧','RECRUITMENT_LEADER',102),
  ('🏗️','招募体系','RECRUITMENT_LEADER',103),
  ('🧾','岗位画像','RECRUITMENT_LEADER',104),
  ('📝','职位描述','RECRUITMENT_LEADER',105),
  ('📣','招募文案','RECRUITMENT_LEADER',106),
  ('📮','渠道招聘','RECRUITMENT_LEADER',107),
  ('🏫','校园招聘','RECRUITMENT_LEADER',108),
  ('🗓️','面试安排','RECRUITMENT_LEADER',109),
  ('🧪','能力测评','RECRUITMENT_LEADER',110),
  ('❓','结构化面试','RECRUITMENT_LEADER',111),
  ('🧩','胜任力模型','RECRUITMENT_LEADER',112),
  ('🪜','候选人漏斗','RECRUITMENT_LEADER',113),
  ('🤝','候选人沟通','RECRUITMENT_LEADER',114),
  ('💌','录用邀约','RECRUITMENT_LEADER',115),
  ('🌱','新人入组','RECRUITMENT_LEADER',116),
  ('🧭','入组引导','RECRUITMENT_LEADER',117),
  ('👨‍🏫','新人培训','RECRUITMENT_LEADER',118),
  ('📊','招募数据分析','RECRUITMENT_LEADER',119),
  ('🏷️','人才标签','RECRUITMENT_LEADER',120),
  ('🗃️','人才库运营','RECRUITMENT_LEADER',121),
  ('🌟','雇主品牌','RECRUITMENT_LEADER',122),
  ('🎯','精准寻访','RECRUITMENT_LEADER',123),
  ('🪄','面试体验','RECRUITMENT_LEADER',124),
  ('🔎','背景了解','RECRUITMENT_LEADER',125),
  ('⚖️','人岗匹配','RECRUITMENT_LEADER',126),
  ('🧑‍🤝‍🧑','团队结构规划','RECRUITMENT_LEADER',127),
  ('🔄','人才盘点','RECRUITMENT_LEADER',128),
  ('📈','梯队建设','RECRUITMENT_LEADER',129),
  ('💬','离组访谈','RECRUITMENT_LEADER',130),
  ('🤍','多元包容','RECRUITMENT_LEADER',131),
  ('🔐','招聘隐私','RECRUITMENT_LEADER',132),
  ('📋','招募SOP','RECRUITMENT_LEADER',133),
  ('🧮','人力预算','RECRUITMENT_LEADER',134),
  ('🪞','招募复盘','RECRUITMENT_LEADER',135),
  ('🧱','任务执行','TEAM_MEMBER',101),
  ('🤝','协同配合','TEAM_MEMBER',102),
  ('📌','任务认领','TEAM_MEMBER',103),
  ('📣','进度同步','TEAM_MEMBER',104),
  ('🆘','及时求助','TEAM_MEMBER',105),
  ('✅','交付意识','TEAM_MEMBER',106),
  ('🧹','收尾能力','TEAM_MEMBER',107),
  ('🧑‍🔧','动手能力','TEAM_MEMBER',108),
  ('🔁','反馈闭环','TEAM_MEMBER',109),
  ('📋','清单管理','TEAM_MEMBER',110),
  ('🧭','按需支援','TEAM_MEMBER',111),
  ('🧑‍🤝‍🧑','团队补位','TEAM_MEMBER',112),
  ('📚','经验沉淀','TEAM_MEMBER',113),
  ('🧪','方案验证','TEAM_MEMBER',114),
  ('🗣️','意见表达','TEAM_MEMBER',115),
  ('👂','积极倾听','TEAM_MEMBER',116),
  ('🛠️','工具运用','TEAM_MEMBER',117),
  ('📦','成果整理','TEAM_MEMBER',118),
  ('🔎','自查自检','TEAM_MEMBER',119),
  ('🎯','任务聚焦','TEAM_MEMBER',120),
  ('📅','截止日期意识','TEAM_MEMBER',121),
  ('🧘','稳定输出','TEAM_MEMBER',122),
  ('🏃','行动迅速','TEAM_MEMBER',123),
  ('🔗','上下游协同','TEAM_MEMBER',124),
  ('🪜','步骤化执行','TEAM_MEMBER',125),
  ('💪','担当意识','TEAM_MEMBER',126),
  ('📍','现场支持','TEAM_MEMBER',127),
  ('🧰','多技能支持','TEAM_MEMBER',128),
  ('📖','规范遵循','TEAM_MEMBER',129),
  ('🌱','成长意识','TEAM_MEMBER',130),
  ('🧩','团队融入','TEAM_MEMBER',131),
  ('🔄','轮岗适应','TEAM_MEMBER',132),
  ('📝','工作记录','TEAM_MEMBER',133),
  ('🏅','交付品质','TEAM_MEMBER',134),
  ('🙌','伙伴支持','TEAM_MEMBER',135),
  ('🧠','好奇心','LEARNING_MEMBER',101),
  ('🏃','快速学习','LEARNING_MEMBER',102),
  ('📖','自主学习','LEARNING_MEMBER',103),
  ('❓','主动提问','LEARNING_MEMBER',104),
  ('📝','课堂笔记','LEARNING_MEMBER',105),
  ('🗺️','学习规划','LEARNING_MEMBER',106),
  ('🎯','学习目标','LEARNING_MEMBER',107),
  ('🔁','刻意练习','LEARNING_MEMBER',108),
  ('🪞','自我反思','LEARNING_MEMBER',109),
  ('📚','知识管理','LEARNING_MEMBER',110),
  ('🔗','知识迁移','LEARNING_MEMBER',111),
  ('🧩','举一反三','LEARNING_MEMBER',112),
  ('🧪','实践验证','LEARNING_MEMBER',113),
  ('🔍','资料查找','LEARNING_MEMBER',114),
  ('🌱','成长型思维','LEARNING_MEMBER',115),
  ('🧑‍🏫','请教导师','LEARNING_MEMBER',116),
  ('👥','同伴学习','LEARNING_MEMBER',117),
  ('📣','学习分享','LEARNING_MEMBER',118),
  ('🧱','基础夯实','LEARNING_MEMBER',119),
  ('🏗️','体系化学习','LEARNING_MEMBER',120),
  ('🧭','方向探索','LEARNING_MEMBER',121),
  ('🛠️','技能训练','LEARNING_MEMBER',122),
  ('⏳','专注力','LEARNING_MEMBER',123),
  ('📅','学习打卡','LEARNING_MEMBER',124),
  ('✅','作业完成','LEARNING_MEMBER',125),
  ('🧠','记忆方法','LEARNING_MEMBER',126),
  ('🧮','计算思维','LEARNING_MEMBER',127),
  ('📄','论文阅读','LEARNING_MEMBER',128),
  ('✍️','学术写作','LEARNING_MEMBER',129),
  ('🎤','答辩练习','LEARNING_MEMBER',130),
  ('🏆','备赛能力','LEARNING_MEMBER',131),
  ('🧑‍🔬','实验能力','LEARNING_MEMBER',132),
  ('💻','在线学习','LEARNING_MEMBER',133),
  ('🌐','跨学科学习','LEARNING_MEMBER',134),
  ('🚀','从零到一','LEARNING_MEMBER',135);

INSERT INTO `talent_role_tag` (`tag_text`, `emoji`, `status`, `sort_order`)
SELECT s.`tag_text`, MIN(s.`emoji`), 1, MIN(s.`sort_order`)
FROM `tmp_talent_role_tag_seed` s
GROUP BY s.`tag_text`
ON DUPLICATE KEY UPDATE
  `emoji` = VALUES(`emoji`),
  `status` = 1,
  `sort_order` = VALUES(`sort_order`);

INSERT IGNORE INTO `talent_role_tag_relation` (`tag_id`, `role_code`)
SELECT t.`id`, r.`code`
FROM `tmp_talent_role_tag_seed` s
INNER JOIN `talent_role_tag` t ON t.`tag_text` = s.`tag_text`
INNER JOIN `project_role` r ON r.`status` = 1 AND (s.`role_code` IS NULL OR r.`code` = s.`role_code`);

DROP TEMPORARY TABLE `tmp_talent_role_tag_seed`;

-- Verification: every current role should return 105.
SELECT r.`code`, r.`name`, COUNT(tr.`tag_id`) AS `tag_count`
FROM `project_role` r
LEFT JOIN `talent_role_tag_relation` tr ON tr.`role_code` = r.`code`
WHERE r.`status` = 1
GROUP BY r.`code`, r.`name`
ORDER BY r.`sort_order`;
